/*
 *  DatabaseConnector.java Copyright (C) 2024 Daniel H. Huson
 *
 *  (Some files contain contributions from other authors, who are then mentioned separately.)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package splitstree6.dialog.analyzegenomes;


import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public class DatabaseConnector {
	public static Connection createSQLiteConnection(String fileName, Boolean readOnly) {
	/*
		final SQLiteConfig config = new SQLiteConfig();
		config.setCacheSize(10000);
		config.setReadOnly(readOnly);

		try {
			return config.createConnection("jdbc:sqlite:" + fileName);
		} catch (SQLException e) {
			Basic.caught(e);
		}
		*/
		return createEmptyConnection();
	}

	public static Connection createEmptyConnection() {
		return new Connection() {
			@Override
			public Statement createStatement() throws SQLException {
				return null;
			}

			@Override
			public PreparedStatement prepareStatement(String sql) throws SQLException {
				return null;
			}

			@Override
			public CallableStatement prepareCall(String sql) throws SQLException {
				return null;
			}

			@Override
			public String nativeSQL(String sql) throws SQLException {
				return null;
			}

			@Override
			public void setAutoCommit(boolean autoCommit) throws SQLException {

			}

			@Override
			public boolean getAutoCommit() throws SQLException {
				return false;
			}

			@Override
			public void commit() throws SQLException {

			}

			@Override
			public void rollback() throws SQLException {

			}

			@Override
			public void close() throws SQLException {

			}

			@Override
			public boolean isClosed() throws SQLException {
				return false;
			}

			@Override
			public DatabaseMetaData getMetaData() throws SQLException {
				return null;
			}

			@Override
			public void setReadOnly(boolean readOnly) throws SQLException {

			}

			@Override
			public boolean isReadOnly() throws SQLException {
				return false;
			}

			@Override
			public void setCatalog(String catalog) throws SQLException {

			}

			@Override
			public String getCatalog() throws SQLException {
				return null;
			}

			@Override
			public void setTransactionIsolation(int level) throws SQLException {

			}

			@Override
			public int getTransactionIsolation() throws SQLException {
				return 0;
			}

			@Override
			public SQLWarning getWarnings() throws SQLException {
				return null;
			}

			@Override
			public void clearWarnings() throws SQLException {

			}

			@Override
			public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
				return null;
			}

			@Override
			public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
				return null;
			}

			@Override
			public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
				return null;
			}

			@Override
			public Map<String, Class<?>> getTypeMap() throws SQLException {
				return null;
			}

			@Override
			public void setTypeMap(Map<String, Class<?>> map) throws SQLException {

			}

			@Override
			public void setHoldability(int holdability) throws SQLException {

			}

			@Override
			public int getHoldability() throws SQLException {
				return 0;
			}

			@Override
			public Savepoint setSavepoint() throws SQLException {
				return null;
			}

			@Override
			public Savepoint setSavepoint(String name) throws SQLException {
				return null;
			}

			@Override
			public void rollback(Savepoint savepoint) throws SQLException {

			}

			@Override
			public void releaseSavepoint(Savepoint savepoint) throws SQLException {

			}

			@Override
			public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
				return null;
			}

			@Override
			public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
				return null;
			}

			@Override
			public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
				return null;
			}

			@Override
			public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
				return null;
			}

			@Override
			public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
				return null;
			}

			@Override
			public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
				return null;
			}

			@Override
			public Clob createClob() throws SQLException {
				return null;
			}

			@Override
			public Blob createBlob() throws SQLException {
				return null;
			}

			@Override
			public NClob createNClob() throws SQLException {
				return null;
			}

			@Override
			public SQLXML createSQLXML() throws SQLException {
				return null;
			}

			@Override
			public boolean isValid(int timeout) throws SQLException {
				return false;
			}

			@Override
			public void setClientInfo(String name, String value) throws SQLClientInfoException {

			}

			@Override
			public void setClientInfo(Properties properties) throws SQLClientInfoException {

			}

			@Override
			public String getClientInfo(String name) throws SQLException {
				return null;
			}

			@Override
			public Properties getClientInfo() throws SQLException {
				return null;
			}

			@Override
			public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
				return null;
			}

			@Override
			public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
				return null;
			}

			@Override
			public void setSchema(String schema) throws SQLException {

			}

			@Override
			public String getSchema() throws SQLException {
				return null;
			}

			@Override
			public void abort(Executor executor) throws SQLException {

			}

			@Override
			public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {

			}

			@Override
			public int getNetworkTimeout() throws SQLException {
				return 0;
			}

			@Override
			public <T> T unwrap(Class<T> iface) throws SQLException {
				return null;
			}

			@Override
			public boolean isWrapperFor(Class<?> iface) throws SQLException {
				return false;
			}
		};
	}
}
